name: deploy-website

on: [push, repository_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Project Dependencies
      run: npm ci

    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli@2.12.117

    - name: Build
      run: gatsby build
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.APP_REPO_ACCESS_TOKEN }}

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FtpServer }}
        FTP_USERNAME: ${{ secrets.FtpUsername }}
        FTP_PASSWORD: ${{ secrets.FtpPassword }}
        REMOTE_DIR: /public_html/wikini
        LOCAL_DIR: public
